[metadata]
addr = 0x3050b70
size = 0x280
last_change = 2024-06-13T21:40:16.457747Z

[header]
last_change = 2024-06-13T21:40:16.457747Z
name = "?registerBlockFromDefinition@BlockDefinitionGroup@@QEAAXAEBUBlockDefinition@@_N@Z"
addr = 0x3050b70
