[0x3050bc0]
last_change = 2024-06-13T21:39:30.661045Z
addr = 0x3050bc0
func_addr = 0x3050b70
comment = "possibly inlined ?registerBlockFromDefinition@BlockDefinitionGroup@@QEAAXAEBUBlo\nckDefinition@@_N@Z\n"
decompiled = true
