user = "freddie"
version = "4.1.6"
last_push_time = 2024-06-13T21:40:56.058707Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Updated <FuncHeader: None ?loadResources@BlockDefinitionGroup@@QEAAXAEBVResourcePackManager@@AEBVBlockComponentFactory@@AEBVExperiments@@@Z(args=0); @0x30531a0>"
