user = "freddie"
version = "4.1.6"
last_push_time = 2024-06-13T21:40:16.457747Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Updated <FuncHeader: None ?registerBlockFromDefinition@BlockDefinitionGroup@@QEAAXAEBUBlockDefinition@@_N@Z(args=0); @0x3050b70>"
