user = "freddie"
version = "4.1.6"
last_push_time = 2024-06-13T21:39:49.676371Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Updated <FuncHeader: unsigned long long * ??0HashedString@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z(args=0); @0x3e8bad0>"
